### ISSUE TITLE
Question: how to show data table with respective label in Column Chart of Google Chart API

### ISSUE THREAD

**Issue by oguzAtes** [GoogleWebComponents/google-chart#104]
Hi all, 

how to show data table with respective label in Column Chart of Google Chart API ?
is it possible ?
Like below picture 
Thank you
![image](https://cloud.githubusercontent.com/assets/6254684/14427391/308be434-fffd-11e5-96ad-0ddf4d1f516f.png)

**Comment by wesalvaro** [comment]
Hmm, I've never seen anything like that but you try asking the Google Visualization team.

This project is just a Polymer wrapper that passes options down to them.

**Comment by oguzAtes** [comment]
How can contact Google Visualization team ? thank you

**Comment by wesalvaro** [comment]
@oguzAtes I think this is the proper place: 
https://github.com/google/google-visualization-issues/issues

**Comment by oguzAtes** [comment]
@wesalvaro thank you
