### ISSUE TITLE
URL as datasource can only be used once

### ISSUE THREAD

**Issue by timeu** [GoogleWebComponents/google-chart#105]
When using an URL for loading data via `iron-request` only the first request will work. All consecutive requests (i.e. when the URL changes) will fail with a null exception on this line: https://github.com/GoogleWebComponents/google-chart/blob/master/google-chart.html#L460

The reason is because `google-chart` re-uses a single `iron-request`. However `iron-request` can only be used once. As soon as the `readyState >0` the [send](https://github.com/PolymerElements/iron-ajax/blob/master/iron-request.html#L201) method will return `null` leading to the exception. 

`iron-ajax` for example creates a new instance of `iron-request` for each request (see [here](https://github.com/PolymerElements/iron-ajax/blob/master/iron-ajax.html#L433)). 
`google-chart` should do the same thing. 

I can create a pull request if that's ok ?

**Comment by wesalvaro** [comment]
Sounds good.
