### ISSUE TITLE
Docs:  Add documentation on how to style this element

### ISSUE THREAD

**Issue by aquadisco** [GoogleWebComponents/google-chart#109]
For the paper components, we get a section on Styling in the documentation and are provided with custom CSS properties to work with.  Could some style guidance be added for this element?  I'm not sure of the proper approach.

Looks like many elements classified as "google web components" don't provide guidance.  Youtube does, but that's the only one i noticed.

**Comment by wesalvaro** [comment]
This component is simply a wrapper around the chart library. You'll find the information you're looking for about styling your charts at the [Google Visualization site](https://developers.google.com/chart/interactive/docs/basic_customizing_chart). There is also an example on the demo page of this component.

**Comment by wesalvaro** [comment]
There are no CSS mixins that can be used with this element at the current time, so there is nothing to document.
