### ISSUE TITLE
Closure compilation fails

### ISSUE THREAD

**Issue by vderosa** [GoogleWebComponents/google-chart#110]
Hi,
it looks like closure compilation fails for this component, despite the annotations. For example in google-chart.html the annotation @type array should be @type Array. Changing this triggers further type issues.

Is there any plan to fix this?

**Comment by wesalvaro** [comment]
Sure, the annotations shouldn't be wrong. I think it just hasn't ever been compiled by anyone over here.

**Comment by addyosmani** [comment]
That's likely correct. If anyone is interested in submitting closure compiler fixes that would make the element compatible with builds, I'm sure we'd be happy to review a PR.

**Comment by wesalvaro** [comment]
I've updated some of these types in #127 
However, I still think it's wrong for the closure compiler.
I've yet to look in detail at compiling a Polymer element, but an `@type` should look more like:

    @type {Array|Object|string|undefined}

than what it is now.

**Comment by wesalvaro** [comment]
Ah. Figured it out. Yeah, let's get this in with #127 for version 1.1.0
