### ISSUE TITLE
Not loading Google Charts correctly according to Google Charts docs

### ISSUE THREAD

**Issue by cbelden** [GoogleWebComponents/google-chart#112]
The Google Charts documentation highlights a particular way to load current/frozen versions of the Google Charts API to ensure the latest stable version of the Google Charts library is loaded.

[From the docs](https://developers.google.com/chart/interactive/docs/basic_load_libs):

Old loading code:
```
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
</script>
```

New loading code:
```
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {packages: ['corechart']});
  google.charts.setOnLoadCallback(drawChart);
</script>
```

**Comment by cbelden** [comment]
Any update on this?

**Comment by ebidel** [comment]
The old way will still work, correct? Is there anything the new way gets you?

Feel free to send a PR for an updated snippet.

**Comment by cbelden** [comment]
Hi ebidel, thanks for getting back to me.

I sent a PR, and am currently failing the CLA check. I am a Google employee, and I'm part of the Google GitHub org; however, I use my personal email for this account. Is that an issue?

**Comment by ebidel** [comment]
You should link your github username on go/github and it'll get picked up by the CLA.

**Comment by fmauNeko** [comment]
There's a regression with this, it is not possible to call back google.charts.load() to load another package.

The demo page itself is broken starting with the table, which displays `Error: google.charts.load() cannot be called more than once with version 45 or earlier.`

Switching the version from `'current'` to `'upcoming'` triggers another error, `TypeError: ctor is not a constructor`, at google-chart.html:69 in chartConstructor().
