### ISSUE TITLE
"google.charts.load() cannot be called more than once with version 45 or earlier"

### ISSUE THREAD

**Issue by jitadash** [GoogleWebComponents/google-chart#118]
google-chart type="treemap" stopped working with error "Error: google.charts.load() cannot be called more than once with version 45 or earlier." same for gauge charts as well in the polymer web page

**Comment by ebidel** [comment]
What version of the component are you using?

**Comment by jitadash** [comment]
i am using the latest version of google chart. Even on the polymer page of google components "https://elements.polymer-project.org/elements/google-chart" in the demo link, those components doesnt work anymore.

Here's a table chart:

Error: google.charts.load() cannot be called more than once with version 45 or earlier.
Here's a timeline chart:

Error: google.charts.load() cannot be called more than once with version 45 or earlier.

**Comment by ketile** [comment]
I get the same error as @jitadash on several of the charts on the [Polymer Chart Element](https://elements.polymer-project.org/elements/google-chart?view=demo:demo/index.html&active=google-chart) page.

**Comment by ebidel** [comment]
This is a known issue. See https://github.com/GoogleWebComponents/google-chart/pull/114. 

@wesalvaro wdyt? Should we roll back to your loading method?

**Comment by jitadash** [comment]
Hi ebidel,

Will this issue be resolved soon?

**Comment by fmauNeko** [comment]
It seems that 'current' still points to '44' even though it should have been switched to '45' on Monday, June 13th.
I think the best option would be to force loading of '45' and to switch to ChartWrapper as @wesalvaro said in #114.

**Comment by ebidel** [comment]
I'm seeing infinite loop issues with using 'upcoming'/45 as as a version. Working with the team to figure out what's up.

**Comment by wesalvaro** [comment]
Sorry, just seeing this.
If there is a timeline to fix this with the new loading method, I say keep it as is and refer to a previous version for loading the old way. If there is no delivery date for this feature (as was the case when I looked into this before), then I say we go ahead and roll it back.

**Comment by wesalvaro** [comment]
Fixed by #124
