### ISSUE TITLE
Specifying google-charts attributes with " results in error msgs

### ISSUE THREAD

**Issue by phidias51** [GoogleWebComponents/google-chart#119]
I'm not sure if this is a code bug, or a documentation bug, but after spending the better part of a day dealing with vague error messages I thought I should report it.  Apparently if you specify google-chart tag attributes using double-quotes, exceptions will be thrown.  For example, if you specify options using 

```
<google-chart  options="{'title': 'Distribution of days in 2001Q1'}"
  cols="[{'label':'Month', 'type':'string'}, {'label':'Days', 'type':'number'}]"
```

Most people use " for attributes as this is the HTML and XML standard and it's what we're used to.  However, in this case apparently the attributes are converted into JSON and single ticks around a key or value (inside the options/cols/rows attributes) cause parsing problems.

Could you update the documentation to explicitly state (in bold or otherwise) that the attributes must be specified "exactly as they are in the documentation", and explain the double- vs single-quote problem.

**Comment by ebidel** [comment]
This is documented in Polymer'd API docs. If you're using JSON directly in an attribute it needs to be valid JSON (double quotes for keys. https://www.polymer-project.org/1.0/docs/devguide/properties#configuring-object-and-array-properties

DO you want to send a PR that adds the note to the google-chart docs?

**Comment by phidias51** [comment]
It would be useful to have that section of the doc repeated or re-emphasized in the google-chart docs.
