### ISSUE TITLE
LineChart: vAxis line hides/shows depending on X value of first point

### ISSUE THREAD

**Issue by tiagomapmarques** [GoogleWebComponents/google-chart#120]
Simple example:
https://jsfiddle.net/zu27thkn/1/

Comment / uncomment the variables in lines 5 and 7.

**Comment by wesalvaro** [comment]
Toggling the value for me does not affect the display of the chart.
Most likely, this was a temporary bug with the Google Charts library (not this Polymer element) and it has been fixed.
