### ISSUE TITLE
Some charts in the demo don't work anymore

### ISSUE THREAD

**Issue by cwayfinder** [GoogleWebComponents/google-chart#128]
There is message instead of a chart:
Error: google.charts.load() cannot be called more than once with version 45 or earlier.

![image](https://cloud.githubusercontent.com/assets/355902/16978648/96a00b68-4e65-11e6-8734-c7feea21a8ae.png)

**Comment by wesalvaro** [comment]
Yes, this is a known issue that was fixed with #124. Thank you for the report. The new version 1.10.0 will be available very soon.
