### ISSUE TITLE
Title as attribute, rather than option

### ISSUE THREAD

**Issue by theefer** [GoogleWebComponents/google-chart#13]
AFAICS, there is currently no way to data-bind the title of a graph, as expressions don't seem to be supported within an object attribute, e.g.

``` html
<!-- doesn't work -->
<google-chart options='{"title": {{someTitle}} }'></google-chart>
```

One solution would be to expose this option (and perhaps others?) as its own attribute, so we could then do:

``` html
<google-chart title="{{someTitle}}"></google-chart>
```

If I'm missing something and data-binding _is_ possible, please let me know!

**Comment by krainboltgreene** [comment]
Is there a particular reason this isn't using the `data-` microformat? Seems perfect.
