### ISSUE TITLE
Google Chart demo fails for Table, Timeline, Three Gauges..

### ISSUE THREAD

**Issue by pbx9959** [GoogleWebComponents/google-chart#133]
https://elements.polymer-project.org/elements/google-chart?view=demo:demo/index.html&active=google-chart
Demo fails with 
"Here's a timeline chart:

Error: google.charts.load() cannot be called more than once with version 45 or earlier."

**Comment by wesalvaro** [comment]
This was fixed in #124

**Comment by pbx9959** [comment]
See the URL as posted above, the demo is still failing.

**Comment by wesalvaro** [comment]
Thank you. Yes, the version currently being demo'd by the Polymer elements catalog is out-of-date and does not have the needed fix. We will be following the catalog update in #136
