### ISSUE TITLE
Update Polymer Element Catalog with google-chart@1.1.0

### ISSUE THREAD

**Issue by joaovieira** [GoogleWebComponents/google-chart#136]
Not sure who owns that project, but would be nice to update to the latest version, as the API (specially the `.redraw()` vs `.drawChart()`) has been updated :)

**Comment by wesalvaro** [comment]
@ebidel would know the most about getting this updated.

**Comment by ebidel** [comment]
@tjsavage

**Comment by wesalvaro** [comment]
On this note, I took a look at updating the `gh-pages` branch of this repository, as it is very out-of-date, but didn't know the proper process.

**Comment by tjsavage** [comment]
Adding @blasten who can bump the catalog

**Comment by tjsavage** [comment]
This has now been updated: https://elements.polymer-project.org/elements/google-chart
