### ISSUE TITLE
Parameter for configuring locale/language

### ISSUE THREAD

**Issue by Scarygami** [GoogleWebComponents/google-chart#145]
Currently the charts are always loaded with the default language `en`.

It would be nice to be able to configure this behavior.

For reference: https://developers.google.com/chart/interactive/docs/basic_load_libs#loadwithlocale

**Comment by wesalvaro** [comment]
So, we'd probably want to do this either as a parameter to the loader or implicitly. I think implicitly might be better, but I'm not positive that it's possible.

### Loader
```html
<google-chart-loader lang="es"></google-chart-loader>
```

### Implicitly
```html
<html lang="es">
```

**Comment by Scarygami** [comment]
I like the implicit approach.

Replacing [the load command](https://github.com/GoogleWebComponents/google-chart/blob/master/google-chart-loader.html#L157) with this should do the trick:
```
google.charts.load('current', {
  'packages': packages,
  'language': document.documentElement.lang || 'en'
});
```

I can send a PR for this if you want.

**Comment by wesalvaro** [comment]
LGTM.
If you want to send a PR, that'd be great!
Thanks,
-Wes
