### ISSUE TITLE
Pushing data not working with data binding

### ISSUE THREAD

**Issue by anthfran** [GoogleWebComponents/google-chart#147]
Here's my chart:
```
<google-chart
    type='combo'
    options='{"title": "Return on Investment", "seriesType": "bars", "series": {"2": {"type": "line"}}}'
    data={{graphData}}>
</google-chart>
```

Initialized property for {{graphData}}
```
graphData: {
    type: Array,
    value: [["Legend", "Principle", "Net Worth", "Return"],["Year 0", 0, 0, 0]],
    notify: true
}
```

If I do the following, data is added to graphData and the chart is updated when the page loads
```
ready: function () {
    this.push('graphData', ["Year 2"), 1000, 1200, 200]);
},
```

However, if I have a button that does a calculations and tries to push data to the array.. nothing happens. The same submit button is able to push data to plain text data bindings which update on the page just fine.
```
submit: function () {
    this.push('graphData', ["Year 2", 1000, 1200, 200]);
}
```

**Comment by anthfran** [comment]
Never mind.. solved it by:
```
var chart = document.getElementById('investChart');
chart.data = [
    ["Legend", "Principle", "Net Worth", "Return"],
    ["Year 1", 100, 200, 100],
    ["Year 2", 200, 400, 200],
];
```

**Comment by wesalvaro** [comment]
You're correct on the issue, though.
`data.slices` is not currently being observed.
If you want to do what you were trying to do, this should get it done:
```js
graphData.push(['Year 2', 1000, 1200, 200]);
this.$investChart.redraw();
