### ISSUE TITLE
Line chart with bar chart- bar width unable to fixed

### ISSUE THREAD

**Issue by rajan-g** [GoogleWebComponents/google-chart#149]
Hi, 
   I have using google chart,  It is mixed of line and bar chart, up to few day's ago bar width is fixed one, but now  I unable to fix that bar size, my plunker is  https://plnkr.co/edit/Wb9tbG3k36tR0QZDVu4u. While I am check with browser bar start form some wrong axis, kindly help me to fix this issue, I hope It is not a data issue, in case it is a data issue let me know Thank you advance

**Comment by wesalvaro** [comment]
Hi, you've asked this question in the wrong place.
This is just for the Polymer-ized element for Google Charts.
You need to [ask the actual Google Visualization team](https://github.com/google/google-visualization-issues/issues) about this.
