### ISSUE TITLE
Does not work on IE 11

### ISSUE THREAD

**Issue by sonkanit** [GoogleWebComponents/google-chart#150]
Demo page is not working on IE 11
https://elements.polymer-project.org/elements/google-chart?view=demo:demo/index.html&active=google-chart

**Comment by Scarygami** [comment]
This should be fixed with https://github.com/GoogleWebComponents/google-chart/pull/146 once a new version of the component is released.

**Comment by wesalvaro** [comment]
Should be in the 1.1.1 version.
