### ISSUE TITLE
Bubble Charts - hide X Y coordinates from bubble tooltip

### ISSUE THREAD

**Issue by pm30** [GoogleWebComponents/google-chart#154]
When I mouse hover on any bubble, it shows me X, Y co-ordinates along with my other data. I would like to hide coordinates. In some other types of charts, I see tooltip customization is possible, however currently it's not supported by bubble chart.

**Comment by wesalvaro** [comment]
I'm not sure what you mean. [The demo for Bubble Chart](https://elements.polymer-project.org/bower_components/google-chart/demo/index.html) does not show X nor Y. This component is simply a wrapper around the actual gViz code. If you cannot figure out the solution from the demo page, you should post your question (and preferably, screenshots) to [this issues page](https://github.com/google/google-visualization-issues/issues).
