### ISSUE TITLE
Assign ID in chart elements

### ISSUE THREAD

**Issue by eduardodallmann** [GoogleWebComponents/google-chart#156]
I need to assign ID to the title and subtitled chart, to use the onclick event.

I'm testing like this:
`$("svg g:eq(0) text:eq(0)").attr('id','gtitle');`
But as the chart is created dynamically, sometimes, the title element is in a different position.

Also I have used:
`$('text:textEquals("Availability of equipment")').attr('id','gtitle');`
The onclick event title is used by the user to change the title, but some special characters that the user can use break the search code.

An official feature to assign ID in chart elements? Or some infallible code to locate element and assign an ID?

**Comment by wesalvaro** [comment]
This is really just a wrapper around the real google-chart visualization and your question seems better poised for that team. You should copy-paste your question here:
https://github.com/google/google-visualization-issues/issues

**Comment by wesalvaro** [comment]
For what it's worth, I think, given current constraints, you're going with a decent approach.
