### ISSUE TITLE
Cannot read property 'load' of undefined

### ISSUE THREAD

**Issue by sivaramgollapudi** [GoogleWebComponents/google-chart#158]
Error thrown when datatable object assigned to data property.
i have downloaded gviz-api.js and referenced as below  along with other reference

`<script type="text/javascript" src="gviz-api.js"></script> 
<google-chart
        type='bar'
        options='{"title": "Leave Chart"}'
        data='{{leaveChartDataString}}'>
      </google-chart>`

and the iron-ajax handle response to prepare datatable as below... 

`handleLeaveChartAjaxResponse : function(){
         this.chartDataTable= new google.visualization.DataTable();
         this.chartDataTable('string','Description');
          this.chartDataTable('number','Value 1');
          this.chartDataTable('numbmer','Value 2');
          this.chartDataTable('number','Value 3');
          for( var resultObj in this.ChartAjaxResponse){
            this.chartDataTable.addRows([
              ['Description 1', 11,20,10],
              ['Description 2', 2,1,2],
              ['Description 3', 2,3,2],
              ['Description 4', 2,1,1]
            ]);`

**Comment by wesalvaro** [comment]
That file is not for actual use in a project. It only serves to help IDEs do auto-complete.
If you look at the contents, there is no code, only empty function definitions.
