### ISSUE TITLE
Add version property

### ISSUE THREAD

**Issue by ltc** [GoogleWebComponents/google-chart#159]
It would be useful to add a "version" string property to google-chart to load a different version of the charts library.  This can be a specific version or the special strings, "upcoming" and "current".  This will be useful when testing out upcoming releases or freezing an app to a specific version.

This would also be consistent with google-map, which also offers a version string property:
https://elements.polymer-project.org/elements/google-map#property-version

Details: https://developers.google.com/chart/interactive/docs/basic_load_libs 

I'll send a PR that adds the version string property to google-chart and google-chart-loader.

**Comment by rslawik** [comment]
Google Charts library can be loaded with custom settings - see the `load` function introduce in #245. Example usage in `custom-load-test`.

It is not a property because the library is loaded only once globally.
