### ISSUE TITLE
`ready` event doesn't seem to fire after changing chart type

### ISSUE THREAD

**Issue by wesalvaro** [GoogleWebComponents/google-chart#162]
Simply changing a chart type does not trigger the `ready` event to be fired again for some reason. It seems, that, the chart library itself doesn't fire it... I have no idea what's going on.
- A new chart is created.
- `draw` is called on the new chart.
- Yet no event is fired after draw.

Doesn't seem to matter which chart types are being tested.

**Comment by tgensol** [comment]
Same issue here

**Comment by wesalvaro** [comment]
@tgensol I think the issue still might lie in this element, but I haven't spent much time trying to track it down. I don't know how this would be an issue with the actual Google Visualization API but I was stumped when I tried to figure it out back in October. If you want to help find the issue, that would be great.

**Comment by rslawik** [comment]
It seems to work after migration to `ChartWrapper`.
Example: https://jsbin.com/zowujipigi/edit?html,output
