### ISSUE TITLE
When only 1 record provided axis date shown is always 1st january

### ISSUE THREAD

**Issue by Junikorn** [GoogleWebComponents/google-chart#165]
$0.set('rows', [[new Date('2016.09.09'), 2, 4]]);
$0.set('type', 'line')
$0.set('cols', [{"type":"date","label":"Time"},{"type":"number","label":"Morning session"},{"type":"number","label":"Evening session"}]);
$0.set('options', {"title":"Average session yield","chartArea":{"left":80,"width":863,"top":40,"height":260},"curveType":"function","pointSize":4,"hAxis":{"title":"Date","format":"dd.MM"},"vAxis":{"title":"Session yield (kg)"},"legend":{"position":"bottom"}});

**Comment by wesalvaro** [comment]
Hi!

You'll want to ask this question in a different forum.
See here: https://github.com/google/google-visualization-issues/issues
