### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by inesferreira** [GoogleWebComponents/google-chart#167]
I create a projet using Google Chart.
When i added the project to IIS, the jquery start to give errors:
net::ERR_CONNECTION_REFUSED

In every xhr.send( ( s.hasContent && s.data ) || null );

Can you hep me?

PS: In localhost it works ok.

**Comment by wesalvaro** [comment]
I'm sorry, I'm not sure where to start with helping you address this issue.

It doesn't seem to be related to this element, either.
