### ISSUE TITLE
Invalid JSON string: {"title":"Days in a month"}

### ISSUE THREAD

**Issue by eitch** [GoogleWebComponents/google-chart#169]
I'm trying to use google-chart in my application, but the demo does not work in my project. I have the following and when rendered it says: Invalid JSON string: {"title":"Days in a month"}

    <link rel="import" href="../../bower_components/polymer/polymer.html">
    <link rel="import" href="../../bower_components/paper-card/paper-card.html">
    <link rel="import" href="../../bower_components/paper-material/paper-material.html">
    <link rel="import" href="../../bower_components/iron-icons/iron-icons.html">
    <link rel="import" href="../../bower_components/iron-icons/av-icons.html">
    <link rel="import" href="../../bower_components/iron-list/iron-list.html">
    <link rel="import" href="../../bower_components/google-chart/google-chart.html">

    <link rel="import" href="./c-shared-styles.html">
    <link rel="import" href="./c-icons.html">

    <dom-module id="c-insights">

      <template>

        <style include="c-shared-styles">
          :host {
            display: block;
          }

          google-chart {
            height: 300px;
            width: 400px;
          }

        </style>

        <div class="container">

          <google-chart
              type="area"
              options='[[chartOptions]]'
              cols='[[cols]]'
              rows='[[rows]]'>
          </google-chart>

        </div>

      </template>

      <script>
        Polymer({
          is: "c-insights",

          properties: {
            insights: {
              type: Array,
              value: []
            },

            chartOptions: {
              type: Object,
              value: {
                "title" : "Days in a month"
              }
            },

            cols: {
              type: Array,
              value: [
                {
                  "label": "Month",
                  "type": "string"
                },
                {
                  "label": "Days",
                  "type": "number"
                }
              ]
            },

            rows: {
              type: Array,
              value: [
                ["Jan", 31],
                ["Feb", 28],
                ["Mar", 31],
                ["Apr", 30],
                ["May", 31],
                ["Jun", 30]
              ]
            }
          }
        });
      </script>
    </dom-module>

**Comment by wesalvaro** [comment]
Try using an example from the demo page and see how it goes. Also, when
your property values are objects and arrays, you should be creating them
with a function.

**Comment by eitch** [comment]
I've changed my source to the following, with the same error:

        <div class="container">
            <google-chart
                    type="area"
                    options='{"title": "Days in a month"}'
                    cols='[ {"label": "Month", "type": "string"},{"label": "Days", "type": "number"} ]'
                    rows='[ ["Jan", 31] , ["Feb", 28] , ["Mar", 31] , ["Apr", 30] , ["May", 31] , ["Jun", 30] ]'>
            </google-chart>
        </div>

**Comment by eitch** [comment]
And i also tried by defining the properties using function. No change.

**Comment by wesalvaro** [comment]
Still, try one of the examples from the demo page and tweak it. I see
nothing wrong with your code and this element does no JSON parsing of the
options (it's a normal object). So my first guess is it might be the
polymer setup.

**Comment by eitch** [comment]
You're right. The issue was due to a problem with my phonegap configuration. Thanks anyhow and sorry for disturbing you.

**Comment by wesalvaro** [comment]
No problem. Glad you were able to get it sorted!
