### ISSUE TITLE
Material design charts options don't match API

### ISSUE THREAD

**Issue by mattppp** [GoogleWebComponents/google-chart#172]
Looking at the material design [demo](https://elements.polymer-project.org/elements/google-chart?view=demo:demo/index.html&active=google-chart) the title doesn't show up even though it's included in the demo code.

I'm having the same issue with my own usage of md-bar where vAxis and hAxis options don't appear on the chart, I can't seem to affect the legend placement, or add a title. One thing that is working is `stacked: true` even though the documentation specifically asks for `isStacked: true`. 

Looking through the [docs](https://developers.google.com/chart/interactive/docs/gallery/barchart#creating-material-bar-charts), it seems like MD charts needs to use the `convertOptions` function in order for options to work. 

Is there something I am missing or is `convertOptions` just not implemented in this element for now? I don't see anything like `chart.draw(data, google.charts.Bar.convertOptions(options))` in this element's source code.

**Comment by mattppp** [comment]
Found a few solutions to my concerns.

1. `title` property needs to be set inside of `chart`. This will fix the demo. 

2. `isStacked` was changed to `stacked` but the documentation wasn't updated yet. A discussion about it can be found [here](https://github.com/google/google-visualization-issues/issues/2143).

3. The `google` object is exposed in `google-chart` so you can use `google.charts.Bar.convertOptions(options)` inside of Polymer. Might be useful to add this to documentation. vAxis.format on MD charts only works with the options converted.

**Comment by marko911** [comment]
I dont seem to be able to get that google object. Is it no longer exposed ?

**Comment by wesalvaro** [comment]
Cool, thanks for the follow-up. I'll fix the demo.
The `google` object is no longer exposed. You can access the `google` global variable after the library has been loaded. In general, I didn't want to support having to convert the options in this element and leaving that up to the user to put the options into the new format themselves.
