### ISSUE TITLE
Add `wordtree` chart type

### ISSUE THREAD

**Issue by pchhibber** [GoogleWebComponents/google-chart#173]
My team has been working with polymer for a lot of projects, and we're considering using the chart component.

Could you please add support for [word trees.](https://developers.google.com/chart/interactive/docs/gallery/wordtree#full)

As per the [current documentation](https://elements.polymer-project.org/elements/google-chart), only the following types are supported.

`area, bar, bubble, candlestick, column, combo, geo, histogram, line, pie, scatter, stepped-area, treemap`

Thanks.

**Comment by wesalvaro** [comment]
```
package: wordtree
google.visualization.WordTree
```
