### ISSUE TITLE
Add `sankey` chart type

### ISSUE THREAD

**Issue by Nachtmerrie** [GoogleWebComponents/google-chart#174]
Unfortunately I am forced to manually put a [sankey diagram ](https://developers.google.com/chart/interactive/docs/gallery/sankey) into my Polymer project.

Could you add support for the sankey chart?

I would use a different chart if my type of data allowed it to, but unfortunately this is the only chart that is a match (And it has pretty colours too!)

For @wesalvaro :-) :

```
package: sankey
google.visualization.sankey

```

**Comment by Nachtmerrie** [comment]
I've added it manually in the chart loader and everything is working fine.

```
'sankey': {
      ctor: 'Sankey',
      pkg: 'sankey',
    }
```

```
<google-chart id="powerSankey"
                type='sankey'
                options='{{sankeyOptions}}'
                cols='[{"label": "From", "type": "string"}, {"label": "To", "type": "string"}, {"label": "Weight", "type": "number"}]'
                rows='{{distribution.power}}'
              ></google-chart>
```

**Comment by wesalvaro** [comment]
Cool. I'll put it in right now.
