### ISSUE TITLE
Google Chart option: hAxes title and direction doesnt work together

### ISSUE THREAD

**Issue by ponnex** [GoogleWebComponents/google-chart#178]
Hi I have problem adding title and direction at the same time in hAxes.

When writing `hAxes": [ {"direction": -1} ]` or `hAxes": [ {"title": "Date"} ]` works well but
`hAxes": [ {"title":"Date"},  {"direction": -1} ]` doesnt. 

And I observed that whichever among title and direction comes first in `hAxes": [ {"title":"Date"},  {"direction": -1} ]` is the one that will append on the code e.g. `hAxes": [ {"title":"Date"},  {"direction": -1} ]` Date will show on the graph but direction will not work however, `hAxes": [  {"direction": -1},  {"title":"Date"} ]` direction will work but title doesnt.
```
<google-chart
  id="strmflow"
  type='line'
  options='{"title": "Stream Flow", 
      "vAxes": [ {"title": "Flow Duration Curve"}, {"title": "Module Summary"}, 
               "scaleType": "log"}, {"scaleType": "log"} ], 
      "hAxes": [ {"direction": -1} ],
      "series": [ {"targetAxisIndex": 0}, {"targetAxisIndex": 1} ]}'
  cols='[ {"label":"Date", "type":"string"}, {"label":"Flow Duration Curve", "type":"number"}, 
      {"label":"Module Summary", "type":"number"} ]'
  rows='[ [" ", 0, 0],[" ", 0, 0],[" ", 0, 0] ]'>
</google-chart>
```

**Comment by wesalvaro** [comment]
The chart in your example only has one series.
The `vAxes` and `hAxes` options are an array of objects, one for each series.
You should only be using one object, like so:
```
{"title":"Date", "direction": -1}
```
If you still feel like this is an issue, please [file it against this other project](https://github.com/google/google-visualization-issues/issues), instead. The `google-chart` element is simply a wrapper around it and most issues with chart drawing are unrelated.

**Comment by ponnex** [comment]
Thanks a lot! I already solve this issue by instead of

`'"hAxes": [ {"title":"Date"}, {"direction": -1}, {"title":"Date"}, {"direction": -1} ]'`

use

`'"hAxes": [ {"title": "Date", "direction": -1}, {"title": "Date", "direction": -1} ]'`

Thanks again! :D

**Comment by wesalvaro** [comment]
Yup! That'll do it! Glad you figured it out.
