### ISSUE TITLE
How can I use “google.visualization.*” objects in <google-chart> web component in Polymer 

### ISSUE THREAD

**Issue by dineshshetye** [GoogleWebComponents/google-chart#182]
Is it possible to use core google chart objects (like DataTable or events) from `package google.visualization.*` in Google Polymer component?

I have a webservice returning JSON data (which is not in the DataTable format) and I want to convert it into google.visualization.DataTable object. The error message I get is "Cannot read property 'DataTable' of undefined"

My Custom Polymer event is below:
```
<link rel="import" href="../../bower_components/iron-ajax/iron-ajax.html">
<link rel="import" href="../../bower_components/google-chart/google-chart.html">

<dom-module id="dash-chart">
	<template>
		<style type="text/css">
	      	.google-chart-style {
	    		width: 100%;
	    		height: 90%;
	    	}
	    </style>
		<iron-ajax
		 	auto
		 	url={{url}}
		 	handle-as="json"
		 	on-response="handleResponse">
		</iron-ajax>
		
		<google-chart
				id="myChart"
				type={{type}}
				options={{options}}>
		</google-chart>

	</template>
	<script>
		Polymer({
			is: "dash-chart",
			properties : {
				url: String,
				type: String,
				options: Object,
				data: Array,
				xaxis: Array,
				yaxis: Array,
				fields: Array
			},
			
			convertResultsToDatatable: function(response) {

				console.log(response);
				//DataTable object
				var objDataTable = new google.visualization.DataTable();

				objDataTable.addColumn(this.xaxis[1], this.xaxis[2]);
				objDataTable.addColumn(this.yaxis[1], this.yaxis[2]);

				var afterConversionToDatatable = [[]];
				for(var index in response) {
				    var objVal = response[index];
				    var arr = [];				    
				    for(var key in objVal) {

				    	if(key === this.xaxis[0]) {
				    		if(this.xaxis[1] === 'number') {
				    			arr.push(parseInt(objVal[key]));
				    		} else {
				    			arr.push(objVal[key]);
				    		}
				    	} else if (key === this.yaxis[0]) {
				    		if(this.yaxis[1] === 'number') {
				    			arr.push(parseInt(objVal[key]));
				    		} else {
				    			arr.push(objVal[key]);
				    		}
				    	}

				    }
				    
				    afterConversionToDatatable[index] = arr;
				}

				console.log(afterConversionToDatatable);
				objDataTable.addRows(afterConversionToDatatable);

				return objDataTable;
			},

			handleResponse: function(data) {
				var rootKey;
				var jsonResult = data.detail.response;
				for(var prop in jsonResult) {
					rootKey = prop;
				}

				//Done so that we do not need to hard code the root object (which changes based with every roxie query)
				var resultNode = jsonResult[rootKey].Results.result_1.Row;
				this.data = this.convertResultsToDatatable(resultNode);
	
			}
		});
	</script>
</dom-module>
```

**Comment by wesalvaro** [comment]
You seem to be in a minority with me about wanting to use an actual `DataTable`.
You can get a `DataTable` from the `google-chart-loader` element:
```js
this.$.loader.dataTable().then(dt => {
  // ... do stuff with the DataTable
});
```

In the v2 update I'm working on, you'll be able to use a new element `google-chart-data` to create a `DataTable` or access the visualization namespace directly:

Here, the result of `data` is a DataTable.
```html
<google-chart-data rows="[[rows]]" cols="[[cols]]" data="{{data}}"></google-chart-data>
```

Alternatively, in your JavaScript, you could create one with the library promise:
```js
new GoogleChartLoader().visualization.then(v => new v.DataTable).then(dt => {
  // ... do stuff with the DataTable
});
```

As always, you can load the library yourself and set your own callback or alternatively, listen for the loader's event to signal the charts library has been loaded.

**Comment by wesalvaro** [comment]
You're getting the error you are because the library has not yet finished loading/setting up.

As for events, you can specify events on the chart directly:
```html
<google-chart events='["foo"]'></google-chart>
```
This will relay any "foo" events from the chart as a Polymer event.

**Comment by wesalvaro** [comment]
Sorry, one last comment, it's worth clarifying that data does not need to be in a `DataTable` proper. It can just be in normal arrays/2D-arrays for rendering.

[Here](https://rawgit.com/GoogleWebComponents/google-chart/v2/demo/index.html) is my v2 demo.

**Comment by dineshshetye** [comment]
@wesalvaro Thanks for taking time out and replying to the question. The problem with my code, like you said was that the library was not being loaded before calling the method to create a DataTable. This was happening to only certain REST services which used to return in less than a second. For remaining services (which would take about 4-5 seconds) to return, the DataTable object was initialized properly. 
I ended up writing an Observer function to call my method (which uses datatable) after the library has been completely loaded. 

```
afterAjaxResponse: function(chartType,ajaxResponse, fields, id) {
        		var loader = document.querySelector('#loader');
        		loader.dataTable(null)
		              .then(dt => {
		                return dt;
		              })
		              .then(function(dt){
		              	fields.forEach(function(element) {
		                	dt.addColumn(element.type, element.label);
		                });
		                  
		                var dtRows = convertTo2DArray(ajaxResponse,  getFields(fields));
		                dt.addRows(dtRows);
		 	        var gc = document.querySelector('google-chart#'+id);
		                gc.data = dt;

		        	  })
		              .catch(function(error){
		                console.error(error);
		              });
			}
```

Before taking the DataTable route I ended up creating 2D-arrays for rows and cols but using out-of-box DataTable  gives you the convenience of using in-built methods like `addColumn`, `addRows` etc. which is really nice.

The V2 update looks really cool. I would definitely try this once it is out in production.

**Comment by wesalvaro** [comment]
looks good but that first `then()` call is superfluous.

**Comment by yglodt** [comment]
I am using <google-chart> V 1.0.4 and need a timeline-chart. Is that possible at all with V1 ?
