### ISSUE TITLE
Update of attributes cols and rows buggy

### ISSUE THREAD

**Issue by arep** [GoogleWebComponents/google-chart#185]
Updating cols and rows with new data containing more or less columns than the existing data gives error, even if I want to update both attributes with new valid data.

However, if setting rows=[] and then cols=[] (in that order!!), and then cols=(actual data) and rows=(actual data), then it works. But only if I do it in this specific order.

See fiddle for example: https://jsfiddle.net/54aro51L/

I would expect that any order works, or there should be a "reset" method maybe.

**Comment by wesalvaro** [comment]
Thanks for the example! I have an idea for why this might be happening...

**Comment by rslawik** [comment]
All three way in the provided example now work: [example](https://jsbin.com/mojejedeza/edit?html,output).

It works now because the underlying `DataTable` is built in a microtask.
