### ISSUE TITLE
Chart Data Leaking to Other Instances

### ISSUE THREAD

**Issue by bennypowers** [GoogleWebComponents/google-chart#187]
I've got N instances of an element which contains a `<google-chart>` version 1.1.2 in its shadow root, as below:

```html
<!-- parent-el template -->
<template is="dom-repeat" items="[[items]]">
    <child-el id="[[item.id]]" item="[[item]]"></child-el>
</template>
<!-- end parent-el template -->

<!-- child-el template -->
<google-chart cols="[[cols]]" rows="[[rows]]"></google-chart>
<!-- end child-el template -->
```
## Child properties
```js
cols: {
  type: Array,
  value: [
    {"label":"Data","type":"string"},
    {"label":"ID","type":"string"},
    {"label":"In","type":"number"},
    {"label":"Out","type":"number"}
  ]
},

rows: {
  type: Array,
  value: [ ]
},
```
```js
_itemChanged: function (nv) {
  if (!nv) {return;}

  for (var i = 0; i < nv.data.length; i++) {
    this.rows[i] = [
      "Data",
      nv.data[i].id,
      nv.data[i].in,
      nv.data[i].out,
    ];
  }
},
```

When the page loads, both charts display the data from the Nth instance of `<google-chart>`. I expected each chart to display its own data.

See also #115

**Comment by bennypowers** [comment]
I'm loading my component with no data and setting it once everything is ready and rendered.

See JSFiddle

https://jsfiddle.net/ww8hg0dp/26/

**Comment by wesalvaro** [comment]
Hey! I figured it out.

Check [here](https://www.polymer-project.org/1.0/docs/devguide/properties#configure-values) for details on declaring default values for your array objects. That fixed it for me. Thanks so much for the demo.

If you have any questions, feel free to ask!

**Comment by bennypowers** [comment]
Yeah that solved it, thanks. Might be worth adding a mention of this to the docs?

**Comment by wesalvaro** [comment]
Using a function to initialize your array and object declared properties is pretty core to Polymer.
It'll affect any element your write or use, not just this one.
