### ISSUE TITLE
Very bad limitation in Google Visualization API - Gantt charts

### ISSUE THREAD

**Issue by ORESoftware** [GoogleWebComponents/google-chart#194]
There are a couple problems I have seen in the google chart API

https://developers.google.com/chart/interactive/docs/gallery/ganttchart

Not sure if this is the right place to submit this issue.

Here are the problems I see: 

1. Google JS api cannot take a string or number and convert it to a Date. This is a problem when I pass the API JSON.stringified data. Dates must be a primitive, yet the Google API cannot interpret a number or a string as a Date. This a huge limitation.

2. I am having trouble scaling things to millseconds, and working with millseconds. I am creating Gantt charts for computer processes, not human processes, so the scale is milliseconds. Is there an easy way to create Gantt charts that can scale to milliseconds? I don't see why not. Should be easy to implement. Just scale it down. But unfortunately it doesn't look like Google API can handle Dates with millisecond data.

Here is an example of the first problem:

```html
<html>
<head>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
    google.charts.load('current', {'packages':['gantt']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Task ID');
      data.addColumn('string', 'Task Name');
      data.addColumn('string', 'Resource');
      data.addColumn('date', 'Start Time');
      data.addColumn('date', 'End Time');
      data.addColumn('number', 'Duration');
      data.addColumn('number', 'Percent Complete');
      data.addColumn('string', 'Dependencies');

      data.addRows(JSON.parse('[["1","regexp.js","some-resource","2017-07-04T22:06:17.465Z","2017-07-04T22:06:18.132Z",null,100,null]]'));

      var options = {
        height: 1200,
        gantt: {
          trackHeight: 30
        }
      };

      var chart = new google.visualization.Gantt(document.getElementById('chart_div'));
      chart.draw(data, options);
    }
  </script>
</head>
<body>
<div id="chart_div"></div>
</body>
</html>
```

above you will clearly see I have worked had to generate date strings, but yet Google API cannot convert them, even though they are entirely valid.

Lame! :)

**Comment by ORESoftware** [comment]
I got it working like so:

```js
   const val = JSON.parse('{{{arrayOfArrays}}}');

      const mapped = val.map(function(item){
         return [item[0], item[1], item[2], new Date(item[3]), new Date(item[4]), item[5], item[6], item[7] ];
      });

      data.addRows(mapped);

      var options = {
        height: 1200,
        gantt: {
          trackHeight: 30
        }
      };

      var chart = new google.visualization.Gantt(document.getElementById('chart_div'));

      chart.draw(data, options);
```

but frankly that was a bit tricky and I think you will make it harder for programming newbies, that it has to be.

**Comment by ORESoftware** [comment]
Yeah so I don't think the Gantt chart handles anything more granular than days. I passed the Chart API two different tasks with different start Date / end Dates that differed by seconds, and the API can't handle that. Considering that the Duration value can take milliseconds, it seems to me incredibly limiting to not also accept milliseconds for start date and end date.

**Comment by wesalvaro** [comment]
The Gantt chart can do more resolution than days. [This example](https://developers.google.com/chart/interactive/docs/gallery/ganttchart#computing-startendduration) shows using minutes but I haven't messed around too much with it myself.

As for the Date issue, how to represent them as strings is addressed [here](https://developers.google.com/chart/interactive/docs/datesandtimes#dates-and-times-using-the-date-string-representation).

Let me know if you have any further questions, but these issues are unrelated to the Polymer element and you could probably get better, more timely help by posting to [the discussion group](https://groups.google.com/forum/#!forum/google-visualization-api) or to [the issue list](https://github.com/google/google-visualization-issues/issues).

**Comment by wesalvaro** [comment]
@ORESoftware I just saw your issue and the post over on the library's issue list. I think that your issue comes when specifying the start Date. As in the example that I posted, the start and end Dates are null. You only need to populate duration, which I tweaked the example and it will show resolutions as high as 0.01 seconds.

**Comment by ORESoftware** [comment]
Thanks for responding to this issue. If I just use a duration, then I won't get the right start time. This is what I am looking for:

<img width="1369" alt="screenshot 2017-07-04 20 39 28" src="https://user-images.githubusercontent.com/11139560/27848288-e7eda150-60f8-11e7-9993-f463da754afe.png">



However to achieve the above, I had do some real gymnastics, like I said, I had to translate milliseconds into days, LOL, it was not pleasant at all.

I clicked the link to find the example that uses minutes for start/end date, I couldn't find it.

**Comment by wesalvaro** [comment]
It looks like you might just want a timeline graph for that.

**Comment by ORESoftware** [comment]
@wesalvaro thanks, do you have a good link for that?

**Comment by ORESoftware** [comment]
Ok, I think this is what you mean: https://developers.google.com/chart/interactive/docs/gallery/timeline

yeah that's probably a lot better..my processes are always independent, whereas Gantt charts have process that are interdependent...thanks!

**Comment by wesalvaro** [comment]
Cool. Let me know if you have any questions.

**Comment by ORESoftware** [comment]
thanks for your help, I finally got this working with Timeline (I was using Gantt before)

<img width="1420" alt="screenshot 2017-12-09 18 19 47" src="https://user-images.githubusercontent.com/11139560/33801341-977fe4ee-dd0d-11e7-813d-404ab6a99f4a.png">

I had this issue
https://stackoverflow.com/questions/47734952/label-color-or-bar-color-by-row-for-google-timeline-chart

but I figured out a solution pretty quickly to that

**Comment by ORESoftware** [comment]
If you know how to add a legend to a Google Timeline chart, I could use one of those

**Comment by wesalvaro** [comment]
For legends, you have two options:
 - Roll your own
 - Label the rows
You also don't need to use one row for each as you have it. It's a bit ... tall ... haha.
I would say something like the [advanced example](https://developers.google.com/chart/interactive/docs/gallery/timeline#an-advanced-example) could fit your needs.

**Comment by sanj79** [comment]
Hi @wesalvaro ,

Is it possible for Gantt chart labels to be placed inside the bars , instead of left aligned ?

**Comment by wesalvaro** [comment]
@sanj79 Please see [here](https://developers.google.com/chart/interactive/docs/gallery/ganttchart) for options on the Gantt chart.

**Comment by tawfikm** [comment]
Hello I have a problem with google gantt chart, I can't see the chart drawing
this is my code:
<script type="text/javascript">

 function sleep(ms) {
		  return new Promise(resolve => setTimeout(resolve, ms));
		}

	  google.charts.load('current', {'packages':['gantt']});
      google.charts.setOnLoadCallback(drawChart);
	  
      
	  function runXHR(url) {
	    const xhr = new XMLHttpRequest();
	    xhr.addEventListener('loadend', handleEvent);
	    xhr.open("GET", url);
	    xhr.send();	
	    return xhr;  
	  }

	async function handleEvent(e) {
	   var tab = [];
	   var data = new google.visualization.DataTable();

		  data.addColumn('string', 'Task ID');
	      data.addColumn('string', 'Task Name');
	      data.addColumn('string', 'Resource');
	      data.addColumn('date', 'Start Date');
	      data.addColumn('date', 'End Date');
	      data.addColumn('number', 'Duration');
	      data.addColumn('number', 'Percent Complete');
	      data.addColumn('string', 'Dependencies');

		var eventInfo = e.srcElement;
		
		jsonData = JSON.parse(eventInfo.response) 
		await sleep(10000);		
		  if (eventInfo.status >= 200 && eventInfo.status < 400) {
		    jsonData.forEach(task => {
		      var taskId = task.idt.toString();
		      var taskName = task.name;
		      var taskResource = task.resources.toString();
		      var taskStartDate = null;
		      var taskFinishDate = new Date(task.finishDate);
		      var taskDuration = 4.0;
		      var taskPcomplete = 10;
		      var taskPredec =  task.prdecessecors.toString();

		       var x = new Array(taskId, taskName, taskResource, taskStartDate, taskFinishDate,daysToMilliseconds(taskDuration), taskPcomplete, taskPredec);

		      tab.push(x);
		    })


		  console.log("Fetch: ", tab);

		  data.addRows(tab);

		  console.log("data: ", data);

	        var options = {
	          height: 275,
	          gantt: {
	            criticalPathEnabled: true,
	            criticalPathStyle: {
	              stroke: '#e64a19',
	              strokeWidth: 5
	            }
	          }
	        };

	      var chart = new google.visualization.Gantt(document.getElementById('chart_div'));

	      chart.draw(data, options);

		  } else {
		    console.log('error!!')
		  }
		
      // console.log(options);
      // console.log(data);

		}
	
     
      function drawChart() {
	  	runXHR('http://localhost:8080/projects/5d3794add2e7cf1b544519f8/tasks')
	     
      }

      function daysToMilliseconds(days) {
        return days * 24 * 60 * 60 * 1000;
      }


</script>
