### ISSUE TITLE
Add passive event listeners to pass Lighthouse audits

### ISSUE THREAD

**Issue by glennphilp** [GoogleWebComponents/google-chart#202]
According to Google's Lighthouse audit, the following doesn't pass the passive event listeners.

https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

![screen shot 2017-10-20 at 2 08 59 pm](https://user-images.githubusercontent.com/2106652/31837961-659b0204-b5a0-11e7-99be-05788326aebd.png)

#minorbug

**Comment by wesalvaro** [comment]
This element does not actually add any event listeners directly. It makes use of the Polymer and Google Visualization event system. This would probably be an issue with the Google Visualization events. Better to file a bug over there: https://github.com/google/google-visualization-issues/issues
