### ISSUE TITLE
Calendar chart legend fixed range

### ISSUE THREAD

**Issue by rafbel** [GoogleWebComponents/google-chart#209]
Is it possible to fix the range for the Calendar chart? 
My legend shows up 0 - 46 because of the values I inserted (like the image below).
![image](https://user-images.githubusercontent.com/14187686/36843132-b1b1486c-1d2c-11e8-8637-8a2910e2f6f3.png)

Is it possible to fix the legend to show a range of 0 - 100 no matter the values I insert?

Thanks.

**Comment by rafbel** [comment]
Ok, this issue can be closed. Figure out how to do it:

![image](https://user-images.githubusercontent.com/14187686/36867659-8c6ad9c2-1d74-11e8-8422-9939a4a4c8d6.png)

**Comment by wesalvaro** [comment]
Cool! glad you figured it out!
