### ISSUE TITLE
loader.js doesn't load after vulcanize project

### ISSUE THREAD

**Issue by vixson** [GoogleWebComponents/google-chart#213]
After optimizing a project using vulcanize https://www.gstatic.com/charts/loader.js would not be able to load up again. it returns a non UTF-8  encode string, and consoles this:

> Uncaught SyntaxError: Invalid or unexpected token loader.js:1

> Uncaught ReferenceError: google is not defined (index.html):33198

**Comment by rslawik** [comment]
Vulcanization is not needed with the ES modules version.
Please reopen the issue if you still experience the problem with the component published on [npm](https://www.npmjs.com/package/@google-web-components/google-chart).

**Comment by vixson** [comment]
Thanks @rslawik
