### ISSUE TITLE
Polymer 3?

### ISSUE THREAD

**Issue by DrNiels** [GoogleWebComponents/google-chart#214]
Is it planned to convert this component to Polymer 3? This would be highly appreciated, since I really enjoy using it.

**Comment by caseylau** [comment]
I really need the polymer3 version too, Maybe we can use [polymer-modulizer](https://github.com/Polymer/polymer-modulizer) to convert it to Polymer3

**Comment by MichaelScript** [comment]
@DrNiels 
@caseylau 
Here is a version we made that works with Polymer 3!
https://github.com/MichaelScript/google-chart

**Comment by naxo8628** [comment]
https://www.npmjs.com/package/google-chart-polymer-3

**Comment by punkratz312** [comment]
@MichaelScript sorry the modules does not work for me. Unfortunately its not possible to submit a issue in the corresponding repo, so I hope this request reaches you.

As you can see, I added the cart but nothing is displayed nor an error is shown in the console.  
![image](https://user-images.githubusercontent.com/8830888/46285217-fe6c6a00-c57a-11e8-926d-1b9cd5c6b247.png)


The components are fetched but nothing happens:
![image](https://user-images.githubusercontent.com/8830888/46285190-e8f74000-c57a-11e8-97b7-7ad9c09fd23c.png)

**Comment by punkratz312** [comment]
+1 polymer 3.0 support would be great

**Comment by MichaelScript** [comment]
@punkratz312 Hey, I can look into this for you when I find some time. Things to make sure are that you have a height and weight for your chart and you're calling the initGCharts method

**Comment by emersonbottero** [comment]
I made my own but i'm really bad with Github. I'm doing another bases on chartist.

**Comment by lukebjerring** [comment]
Since it hasn't been mentioned yet, v3.0.0 _is_ available:
https://www.webcomponents.org/element/@google-web-components/google-chart

**Comment by rslawik** [comment]
Yes, the component has been upgraded to Polymer 3. It can installed from npm. Here's a live demo: https://jsbin.com/taximobici/edit?html,output.
