### ISSUE TITLE
Issue with Scatter chart API

### ISSUE THREAD

**Issue by Mumalo** [GoogleWebComponents/google-chart#215]
I am trying to display a scatter chart with date on X-axis.
The issue is when I pass in my dataList with a specific date range, the chart api adds values to the x-axis

For instance: display results from June 1 to June 30
Expected result:L Chart displays dates between Jun 1 and 30
Actual result: Chart shows dates between Jun 1 and 30 and adds July 3 and July 10
I dont know where these additional values are coming from.
PS: it works as expected when using LineCharts

**Comment by rslawik** [comment]
This seems to be specific to the Google Chart library directly. Issues for the library should be filed on https://github.com/google/google-visualization-issues/issues
