### ISSUE TITLE
timeline chart rows label error

### ISSUE THREAD

**Issue by cirabad117** [GoogleWebComponents/google-chart#217]
Since a time ago, I've used this components in my polymer 2.0 projects, but now, when I try to create a new  timeline chart the labels don't appear correctly

The chart shows the labels like this
![sin titulo](https://user-images.githubusercontent.com/33065606/43150074-a42840e6-8f2e-11e8-95bb-0e47ac818928.png)

this is my code

` <google-chart class="google-chart-class" style="cursor: pointer; width: 1000px;height: 200px;" id="charGoo" selection="{{evento}}" on-google-chart-select="selected"
                            type="timeline" options="[[opciones]]" cols="[[cols]]" rows="{{data}}" on-google-chart-ready='chartLoaded'>
                        </google-chart>`

This error only happens in this project, all my others projects have a normal behavior

**Comment by rslawik** [comment]
This could have been a problem with the shadow DOM. Please reopen if you see this problem in the latest LitElement version.
