### ISSUE TITLE
The README isn't helpful

### ISSUE THREAD

**Issue by z5h** [GoogleWebComponents/google-chart#218]
I'd like to use https://github.com/GoogleWebComponents/google-chart

From the README I followed

>  See https://elements.polymer-project.org/elements/google-chart

From there I clicked "Getting Started" in the header
I read "How do I use a web component?" It says

>  look at its README for the commands to install it.  Most elements today can be installed with Bower.

I already looked at it's README and that didn't help.  
bower.io says "we recommend using Yarn and Webpack or Parcel"

So do choose one of those? It's not clear.

**Comment by rslawik** [comment]
`<google-chart>` is now available on [npm](https://www.npmjs.com/package/@google-web-components/google-chart) and the README has been updated (it includes even a live demo).

Would you like to give it another try? Let us know if the README is not clear.
