### ISSUE TITLE
Setting headerHeight to 0 for Treemap Chart provokes TypeError when hovering the chart

### ISSUE THREAD

**Issue by kevinadda** [GoogleWebComponents/google-chart#219]
A simple way to hide the treemap header is to set its height to 0.

In the documentation, it is clear 0 is an acceptable value (it is also the given default value, which is probably a mistake):
![image](https://user-images.githubusercontent.com/3613657/44046833-fc67c43a-9f2c-11e8-9442-4469eef9d06a.png)

When setting it to 0, the chart works normally, however each time a cell is hovered, a TypeError is thrown:
```
jsapi_compiled_ui_module.js:28 Uncaught TypeError: Cannot read property 'j' of null
    at gvjs_Wz.gvjs_.appendChild (jsapi_compiled_ui_module.js:28)
    at gvjs_Wz.gvjs_.ke (jsapi_compiled_ui_module.js:31)
    at gvjs_eX (jsapi_compiled_treemap_module.js:23)
    at gvjs_$W.gvjs_.Qba (jsapi_compiled_treemap_module.js:36)
    at gvjs_$W.gvjs_.bta (jsapi_compiled_treemap_module.js:36)
    at gvjs_Xn (jsapi_compiled_default_module.js:124)
    at SVGSVGElement.gvjs_Tba (jsapi_compiled_default_module.js:126)
    at SVGSVGElement.b (jsapi_compiled_default_module.js:120)
gvjs_.appendChild @ jsapi_compiled_ui_module.js:28
gvjs_.ke @ jsapi_compiled_ui_module.js:31
gvjs_eX @ jsapi_compiled_treemap_module.js:23
gvjs_.Qba @ jsapi_compiled_treemap_module.js:36
gvjs_.bta @ jsapi_compiled_treemap_module.js:36
gvjs_Xn @ jsapi_compiled_default_module.js:124
gvjs_Tba @ jsapi_compiled_default_module.js:126
b @ jsapi_compiled_default_module.js:120
```

The error disappears when `headerHeight` is not 0.

Here's a fiddle reproducing it, based on the current google chart's treemap documentation page:
https://jsfiddle.net/r2c5pfhv/

**Comment by rslawik** [comment]
This example uses the Google Charts library directly. Issues with the library should be reported on https://github.com/google/google-visualization-issues/issues
