### ISSUE TITLE
Add support for Timeline charts

### ISSUE THREAD

**Issue by dani-gallegos** [GoogleWebComponents/google-chart#23]
It would be great to add support for the Timeline graph.

**Comment by poliveira89** [comment]
:+1:

**Comment by RyanWhite04** [comment]
How is progress going with this?
If you need any help let me know.
@sgomes

**Comment by addyosmani** [comment]
As this issue hasn't really been touched in some time and @sgomes has since moved off to focus on Material Design Lite (and is doing great there), I'm tempted to say it would be useful to get a PR in if folks really want to see this land. It's unlikely to be added in the short term otherwise.

**Comment by wesalvaro** [comment]
PR #88 fixes this.
