### ISSUE TITLE
Mousewheel scroll behaviour on zoom in bubble chart

### ISSUE THREAD

**Issue by Abhijeet-Das** [GoogleWebComponents/google-chart#240]
Hello ,
I made a Google bubble chart and added an explorer object ( 'explorer' : { } ) to zoom along x and y axis. But I noticed the zoom behavior is opposite to what is observed in Google maps.
When the mousewheel is scrolled away from the user, the chart gets zoom out. But the same behavior is reversed in google maps ( scroll away, then by zoom in ).
Similarly,
 When the mousewheel is scrolled towards the user, the chart gets zoom in. But the same behavior is reversed in google maps ( scroll towards, then by zoom out ).

Is there any way to fix this or set any parameter to reverse the mousewheel behaviour !

**Comment by rslawik** [comment]
Please create this issue under [google/google-visualization-issues/issues](https://github.com/google/google-visualization-issues/issues). This component uses Google Charts as is and it looks like changing the zoom-in scrolling direction is not supported.

**Comment by Abhijeet-Das** [comment]
Thanks. I have created this issue under google/google-visualization-issues/issues.

**Comment by rslawik** [comment]
Issue discussed in google/google-visualization-issues#2727.
