### ISSUE TITLE
Link Position from start of the bar

### ISSUE THREAD

**Issue by Nikksmanon** [GoogleWebComponents/google-chart#248]
Please refer to the screenshot: -
![image](https://user-images.githubusercontent.com/33192743/61376905-c3e07d80-a8bf-11e9-8da3-83ff4637e976.png)

Something like above is coming but i wanted something like below: -
![image](https://user-images.githubusercontent.com/33192743/61377293-8b8d6f00-a8c0-11e9-96f9-0abef2382f28.png)

Is there any way we can start arrows from the left corner instead of middle??

**Comment by rslawik** [comment]
This part of the arrow is not customizable. See available options: https://developers.google.com/chart/interactive/docs/gallery/ganttchart#configuration-options

This should be a feature request for the Google Charts library: https://github.com/google/google-visualization-issues/issues
