### ISSUE TITLE
Can't debug the red error in the Gantt Chart

### ISSUE THREAD

**Issue by tawfikm** [GoogleWebComponents/google-chart#249]
Hello I have a problem with google gantt chart, I can't see the chart drawing
this is my JS code using a Rest API:
`<script type="text/javascript">

	  google.charts.load('current', {'packages':['gantt']});
      google.charts.setOnLoadCallback(drawChart);
	  
      
	  function runXHR(url) {
	    const xhr = new XMLHttpRequest();
	    xhr.addEventListener('loadend', handleEvent);
	    xhr.open("GET", url);
	    xhr.send();	
	    return xhr;  
	  }

	function handleEvent(e) {
	   var tab = [];
	   var data = new google.visualization.DataTable();

		  data.addColumn('string', 'Task ID');
	      data.addColumn('string', 'Task Name');
	      data.addColumn('string', 'Resource');
	      data.addColumn('date', 'Start Date');
	      data.addColumn('date', 'End Date');
	      data.addColumn('number', 'Duration');
	      data.addColumn('number', 'Percent Complete');
	      data.addColumn('string', 'Dependencies');

		var eventInfo = e.srcElement;

		jsonData = JSON.parse(eventInfo.response)
		
		  if (eventInfo.status >= 200 && eventInfo.status < 400) {
		    jsonData.forEach(task => {
		      var taskId = task.idt.toString();
		      var taskName = task.name;
		      var taskResource = task.resources.toString();
		      var taskStartDate = null;
		      var taskFinishDate = new Date(task.finishDate);
		      var taskDuration = 4.0;
		      var taskPcomplete = 10;
		      var taskPredec =  task.prdecessecors.toString();

		       var x = new Array(taskId, taskName, taskResource, taskStartDate, taskFinishDate,daysToMilliseconds(taskDuration), taskPcomplete, taskPredec);

		      tab.push(x);
		    })
		  console.log("Fetch: ", tab);

		  data.addRows(tab);

		  console.log("data: ", data);

	        var options = {
	          height: 275,
	          gantt: {
	            criticalPathEnabled: true,
	            criticalPathStyle: {
	              stroke: '#e64a19',
	              strokeWidth: 5
	            }
	          }
	        };
	      var container = document.getElementById('chart_div');
	      var chart = new google.visualization.Gantt(container);

	      chart.draw(data, options);

		  } else {
		    console.log('error!!')
		  }
		
      // console.log(options);
      // console.log(data);

		}
	
     
      function drawChart() {
	  	runXHR('http://localhost:8080/projects/5d3794add2e7cf1b544519f8/tasks')
	     
      }

      function daysToMilliseconds(days) {
        return days * 24 * 60 * 60 * 1000;
      }
</script>`
![gantt_Error](https://user-images.githubusercontent.com/26447417/61970984-2af7e380-afde-11e9-8c3f-367032fba2b4.PNG)

**Comment by rslawik** [comment]
This example uses the Google Charts library directly. Issues with the library should be reported in https://github.com/google/google-visualization-issues/issues
