### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by rslawik** [GoogleWebComponents/google-chart#273]
Migrate only `<google-chart>` and `loader.js`. `<google-chart-loader>` will not be migrated, it will be removed instead (see #272).

**Comment by davidenke** [comment]
@rslawik will there be typings for the components in some form?
So it would be easier to use it e.g. Stencil or to adopt the `IntrinsicElements` stuff for React.

**Comment by rslawik** [comment]
Yes, once the TypeScript version is published to npm.

The release will have some breaking changes (e.g. removal of `<google-chart-loader>`). I was thinking about bundling more breaking changes (like making data not accept urls or even migrating to LitElement which would require manually recreating some Polymer-specific things) in the release to minimise the number of required upgrades. This could take a few weeks though.

So, let me take a closer look and if it feels like more than 2 weeks, I will publish the current version. Does that sound ok?

**Comment by rslawik** [comment]
Typings are included in the npm package now. We even have a TypeScript badge on https://www.npmjs.com/package/@google-web-components/google-chart.
