### ISSUE TITLE
Google Gannt charts

### ISSUE THREAD

**Issue by neowenshun** [GoogleWebComponents/google-chart#275]
Hello , i have been using google gannt charts and im very pleased with it , however there seems to be an issue when using controlwrappers. It shows me this : `All series on a given axis must be of the same data type ` , wondering if google gannt supports controls

**Comment by rslawik** [comment]
We have not implemented any support for `ControlWrapper`s in this web component, so I believe you use them directly. In that case, please report this issue in https://github.com/google/google-visualization-issues/issues.
