### ISSUE TITLE
Unable to render nested chart with a data string

### ISSUE THREAD

**Issue by monkeyhouse** [GoogleWebComponents/google-chart#28]
Hi, quite odd, but I found that the element didn't render when (1) inside another element (2) using a string for the data.

However, it did render when I put the data into a variable. See following not working...

    <html>
    <head>    
    <title>Chart Demo</title>

    <script src="/webcomponentsjs/webcomponents.min.js"></script>
    <link rel="import" href="/google-chart/google-chart.html" />

    <polymer-element name="my-chart" noscript>
    <template>

        <h2>Chart inside template</h2>
        <google-chart type='stepped-area'
                      options='{"title": "Inventory"}'
                      data='[["Month", "Days"], ["Jan", 31], ["Feb", 28], ["Mar", 31], ["Apr", 30], ["May", 31], ["Jun", 30]]'>
        </google-chart>
        <content></content>
        

    </template>
    </polymer-element>

    </head>
    <body unresolved>

    <fieldset>
     <h2>Chart on main.html</h2>
      <google-chart type='stepped-area'
              options='{"title": "Inventory"}'
              data='[["Month", "Days"], ["Jan", 31], ["Feb", 28], ["Mar", 31], ["Apr", 30],  ["May", 31], ["Jun", 30]]'>
      </google-chart>
    </fieldset>

    <my-chart></my-chart>

    </body>
    </html>

So the above code doesn't work, but it quickly works when the data is moved into a variable

    <polymer-element name="my-chart">
        <template>

            <h2>Chart inside template</h2>
            <google-chart type='stepped-area'
                          options='{"title": "Inventory"}'
                          data='{{data}}'>
            </google-chart>
            <content></content>
            

        </template>
        <script>
            Polymer('my-chart', {
                data: [["Month", "Days"], ["Jan", 31], ["Feb", 28], ["Mar", 31], ["Apr", 30], ["May", 31], ["Jun", 30]]
            })
        </script>
    </polymer-element>

**Comment by sgomes** [comment]
Sorry for the late reply, @monkeyhouse, but I finally managed to track this down.

Looks like ```[[ (...) ]]``` is an alternate syntax for ```{{ (...) }}```, which means that Polymer sees the string as something it has to interpret. Adding a space between the square brackets should do the trick:

```data='[ ["Month", "Days"], ["Jan", 31], ["Feb", 28], ["Mar", 31], ["Apr", 30], ["May", 31], ["Jun", 30] ]'```

This should fix your problem, but feel free to reopen this issue if it doesn't go away.
