### ISSUE TITLE
Can't import the library in Vuejs

### ISSUE THREAD

**Issue by Kolawole39** [GoogleWebComponents/google-chart#285]
Hi. I am trying to use the library with Vuejs but I don't know how import it well. 
Here's the line of code I used but it didn't worked at all.
`import google from "@google-web-components/google-chart";
`

**Comment by rslawik** [comment]
Hi, what error are you seeing?

There is no export called `google`, so the import should be:

```
import "@google-web-components/google-chart";
```

The path also needs to be rewritten to a real node_modules path for the browser to accept it. This typically is done automatically by tools like TypeScript, bundlers or es-dev-server. If you don't use any of those tools, the path will look like this (depending on the location of your file):

```
import "../node_modules/google-chart/google-chart.js";
```

**Comment by Kolawole39** [comment]
Okay thanks 🙏🏿

**Comment by rslawik** [comment]
Cool, I assume it worked. Please reopen if it didn't.
