### ISSUE TITLE
Migrate to LitElement

### ISSUE THREAD

**Issue by rslawik** [GoogleWebComponents/google-chart#293]
[LitElement](https://lit-element.polymer-project.org/) is a base class for creating lightweight web components. It is the next generation after Polymer 3.

This component does not use some of the Polymer features (like data bindings), so switching to LitElement will reduce the footprint of this component. The API can stay backwards compatible.

LitElement introduces asynchronous rendering which fits well with Google Charts rendering (i.e. waiting for `'ready'` event). This migration should ideally happen in two steps:
1. switch to the new base class (keeping Google Chart rendering separate from LitElement lifecycle)
2. unify Google Charts rendering with LitElement lifecycle

**Comment by moderndeveloperllc** [comment]
@rslawik Looks like this was done in `4.0.0`?

**Comment by rslawik** [comment]
Only the first step (switching to LitElement) base class is done in 4.0.0.

The second one (unifying the lifecycles) is not complete yet. There are some opportunities for optimisations in LitElement. For example:

- Changing `data` triggers 2 renders (one for the input, one for the internal property). Can this be reduced to 1?
- Can the `updateComplete` promise be synchronised with the `'google-chart-ready'` event?

I'd keep this issue open until I check if those can be implemented without breaking changes.

**Comment by rslawik** [comment]
Closing. This can be revisited when migrating to next version of LitElement.
