### ISSUE TITLE
Load new chart type packages with google.charts.load

### ISSUE THREAD

**Issue by kyleledbetter** [GoogleWebComponents/google-chart#30]
Any plans to implement the new Material Charts from https://developers.google.com/chart/interactive/docs/gallery/barchart#Material and https://developers.google.com/chart/interactive/docs/gallery/columnchart#Material?

**Comment by sgomes** [comment]
Oh, that's new! Thanks, I'll look into this!

**Comment by kyleledbetter** [comment]
Cool! Maybe just an option that toggles this:
> The Material Charts are in beta. The appearance and interactivity are largely final, but the way options > are declared is not. If you are converting a Classic Bar Chart to a Material Bar Chart, you'll want to replace this line: 
> chart.draw(data, options);
> ...with this: 
> chart.draw(data, google.charts.Bar.convertOptions(options));

**Comment by jilt** [comment]
thanks a lot both of you :)

**Comment by albertolobrano** [comment]
I will need this feature so i will take some code from #39 and create a pr if it ok for you

**Comment by satyafantain** [comment]
How can we create Material Design on Google Chart?

**Comment by wesalvaro** [comment]
Currently there are issues with using the Material libraries to draw charts in relation to the google-chart widget. The google.charts.load function may only be called once and loading with google.load yields buggy, inconsistent results. Also, given the differences between the material and non-material charts, i don't think it makes sense to just use a boolean attribute.

**Comment by satyafantain** [comment]
thanks

**Comment by wesalvaro** [comment]
BarChart was committing with #124. I'll hopefully get around to adding and testing the other chart types soon. We'll track all this in #94.
