### ISSUE TITLE
Bug Report: Unexpected behavior for some unicode characters.

### ISSUE THREAD

**Issue by SMSadegh19** [GoogleWebComponents/google-chart#311]
Hi. I have trouble using some Unicode characters.
It works very unexpectedly for some characters and texts and not for some!
For example, it works correctly:
[example 1](https://chart.apis.google.com/chart?cht=p3&chf=bg%2Cs%2Cffffff&chco=0000ff&chs=350x120&chd=t%3A0%2C23%2C4%2C49&chds=0%2C49&choe=UTF-8&chtt=%D8%B3%D9%84%D8%A7%D9%85&chdl=%D8%B3%D9%84%D8%A7%D9%85%D8%AA%D9%8A%D9%8A%7Cs%7C%D8%B3%D9%84%D8%A7%D9%85%7C%E5%9C%8B%E8%AA%9E&chl=0%7C23%7C4%7C49&.png)
But this case, which has only one less character than the previous link, does not work:
[example 2](https://chart.apis.google.com/chart?cht=p3&chf=bg%2Cs%2Cffffff&chco=0000ff&chs=350x120&chd=t%3A0%2C23%2C4%2C49&chds=0%2C49&choe=UTF-8&chtt=%D8%B3%D9%84%D8%A7%D9%85&chdl=%D8%B3%D9%84%D8%A7%D9%85%D8%AA%D9%8A%7Cs%7C%D8%B3%D9%84%D8%A7%D9%85%7C%E5%9C%8B%E8%AA%9E&chl=0%7C23%7C4%7C49&.png)
I also saw [a similar question](https://stackoverflow.com/questions/6541452/does-google-chart-support-utf-8-characters) on StackOverflow that was discussed about this problem. (10 years ago!)
But this problem is not solved yet.

Other examples that don't work:
[example 3](https://chart.apis.google.com/chart?cht=p3&chf=bg%2Cs%2Cffffff&chco=0000ff&chs=350x120&chd=t%3A0%2C23%2C4%2C49&chds=0%2C49&choe=UTF-8&chtt=%D9%82%D9%87%D8%B1%D9%85%D8%A7%D9%86&chdl=%D8%B3%D9%84%D8%A7%D9%85%7C%D8%A7%DA%A9%D8%A8%D8%B1%7C%D8%A7%DB%8C%D8%B1%D8%A7%D9%86%7C%DA%86%DB%8C%D9%86&chl=0%7C23%7C4%7C49&.png)

**Comment by rslawik** [comment]
Hi @SMSadegh19,

This repo is for the `<google-chart>` web component. The provided examples do not use it, so I will close this issue. Please reopen if the web component is affected too.

The examples use Image Chart API https://developers.google.com/chart/image/ which is officially deprecated. Consider migrating to alternatives like `<google-chart>`. See also https://groups.google.com/g/google-chart-api/c/rZtHTyYgyXI.
