### ISSUE TITLE
Bump version of lit-element to 3.0.0

### ISSUE THREAD

**Issue by Stradivario** [GoogleWebComponents/google-chart#314]
Hi guys!

Thank you for the awesome repository!

I am using it from 1 year and i recently updated to lit 2.0.0 and i saw a few versions of lit-html installed inside node_modules.
I have investigated and found out that `google-chart` was to blame so i decided to create a PR bumping the version of `lit-element` to `^3.0.0`.

I have successfully run the tests with status passed

```
> wct --module-resolution=node --npm --simpleOutput -l chrome

Installing and starting Selenium server for local browsers
Selenium server running on port 37663
[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
chrome 94                Beginning tests via http://localhost:8081/components/@google-web-components/google-chart/generated-index.html?cli_browser_id=0
chrome failed to maximize
chrome 94                Tests passed
Test run ended with great success

chrome 94 ()
```

Everything looks cool when i test it also locally.

Cheers!

**Comment by Stradivario** [comment]
https://github.com/GoogleWebComponents/google-chart/pull/313

**Comment by rslawik** [comment]
Thanks for the PR.

We were running `<google-chart>` with Lit 2 internally already too.
