### ISSUE TITLE
Doesn't work on firefox

### ISSUE THREAD

**Issue by ystreibel** [GoogleWebComponents/google-chart#35]
Hi,

When I try to load your demo [link][1] on Firefox 32 for Debian, I have this error : 

> Error: You tried to use polymer without loading it first. To load
> polymer, <link rel="import" href="components/polymer/polymer.html"> 	
> 
> ...Polymer===o&&(window.Polymer=function(){throw new Error('You tried
> to use polyme...

	
[1]: http://googlewebcomponents.github.io/google-chart/components/google-chart/demo.html

**Comment by atotic** [comment]
Works on Firefox with Polymer 1.0.
