### ISSUE TITLE
Adding Markers Geomaps

### ISSUE THREAD

**Issue by jilt** [GoogleWebComponents/google-chart#40]
Adding support for markers geomaps would be greatly appreciated

**Comment by SmokyBob** [comment]
Are you referring to [this] (https://developers.google.com/chart/interactive/docs/gallery/geochart#Markers)
?
I've tested recreating the example from the google-chart api and seems to work.
Here the markup I used:

```html
<google-chart
    type='geo'
    options='{"region": "IT",
        "displayMode": "markers",
        "colorAxis": {"colors": ["green", "blue"]}}'
    data='[
        ["City",   "Population", "Area"],
        ["Rome",      2761477,    1285.31],
        ["Milan",     1324110,    181.76],
        ["Naples",    959574,     117.27],
        ["Turin",     907563,     130.17],
        ["Palermo",   655875,     158.9],
        ["Genoa",     607906,     243.60],
        ["Bologna",   380181,     140.7],
        ["Florence",  371282,     102.41],
        ["Fiumicino", 67370,      213.44],
        ["Anzio",     52192,      43.43],
        ["Ciampino",  38262,      11]
      ]'>
  </google-chart>
```

**Comment by jilt** [comment]
Sorry, couldn't find the displayMode option in any demo file, thanks a lot for sharing :)

I used the renderChart function (from google jsapi element) to generate the chart, I probably need to replace it with drawMarkersMap() using geochart package while loading the viz, I'm generating the object using javascript to be able to load a google sheet resource for data

**Comment by SmokyBob** [comment]
@jilt As this is not a bug or a feature request please close the issue.
If you need any help with your implementation please use StackOverflow (maybe post the Link here to move the conversation from here to there).
With a bit of sample code in the SO question you could get better pointers on how to implement the data loading and the chart rendering (ex. using template binding and core-ajax or the google-sheet element).

**Comment by jilt** [comment]
I'm closing the issue now, the code I'd like you to have a look at is this:

https://github.com/jilt/sheets-marker-chart
