### ISSUE TITLE
Google chart not visible when inside an element template

### ISSUE THREAD

**Issue by peduxe** [GoogleWebComponents/google-chart#48]
The google-chart just displays if outside a dom-module template, the element is present in the document and takes up it's space but isn't being displayed.

demo: https://peduxe.herokuapp.com/google-chart.html

**Comment by atotic** [comment]
Can't load example:

An error occurred in the application and your page could not be served. Please try again in a few moments.
If you are the application owner, check your logs for details.

**Comment by peduxe** [comment]
It's indeed available now.

**Comment by atotic** [comment]
Ah, replace `rows='[["Jan", 31]` with `rows='[ ["Jan", 31]`
Known bug in binding parsing in core Polymer.
Page also does not display in FF at all, not sure why.

**Comment by peduxe** [comment]
@sjmiles Said it needs to import the Polymer lib asynchronously with the HTMLImport polyfill to work with FF. To what comes to the bug it's true, adding spaces fixed it.
