### ISSUE TITLE
Chart size to default with service worker

### ISSUE THREAD

**Issue by gary-qi** [GoogleWebComponents/google-chart#52]
I have a chart in a paper-material with certain height 400px in polymer starter kit with service worker.

It works fine if it's in home page/route. "/"

If it's not in "/" route, when you change route to it, it shows smaller size 200px high, assume it's default

If I turn off service worker, it works fine again. It seems caching could not get my style height 400px for google-chart

**Comment by gary-qi** [comment]
to be specific: with service work on, if the following is not drawn at start, when it's cached, the chart height will be 200px
```
<style>
google-chart {
	height: 400px;
	width: 100%;
}
</style>
<template>
    <paper-material elevation="1">
      <google-chart
      type='pie'
      options='{"title": "Google Chart Test", "is3D":true}'
      cols='[ {"label":"Type", "type":"string"}, {"label":"Numbers", "type":"number"} ]'
      rows='[ ["Outdoor", 870],["Indoor", 2670],["Hybrid", 3183] ]'>
      </google-chart>
    </paper-material>
</template>
```

**Comment by gary-qi** [comment]
I can re-drawChart in resize event to fix this. Is this still a minor bug?

**Comment by msuchecki** [comment]
Could you please be more specific how to workaround this issue?

**Comment by ebidel** [comment]
This sounds like a caching bug with service worker and not a bug in the element. I'm not sure why SW would have an effect here.
