### ISSUE TITLE
Using with polymer 5.5

### ISSUE THREAD

**Issue by shanika** [GoogleWebComponents/google-chart#53]
I tried to use google-chart with polymer 0.5.5. Is it possible to do that? I have selected the correct versions of polymer.html and webcomponents.html at the time of installation via bower. But I get following error when I'm trying to use a basic pie chart.
<log>
Uncaught Element name could not be inferred.element @ polymer.js:10274(anonymous function) @ iron-request.html:110
</log>

**Comment by SmokyBob** [comment]
@shanika to use the component with 0.5.5, you need to install version 0.2.1 of the element with the following command
> bower install GoogleWebComponents/google-chart#0.2.1

The latest version is based on Polymer 1.0 and the dependencies are with the new iron-elements instead of core-elements

**Comment by shanika** [comment]
I did as you mentioned and got it working. Thanks a lot. Hoping to move to Polymer 1.0 soon. :)

**Comment by ebidel** [comment]
Closing :)
