### ISSUE TITLE
Break this out into multiple components

### ISSUE THREAD

**Issue by krainboltgreene** [GoogleWebComponents/google-chart#57]
`<google-chart-line>`
`<google-chart-pie>`
`<google-chart-histogram>`
`<google-chart-etc>`

**Comment by ebidel** [comment]
What's the reasoning?

**Comment by krainboltgreene** [comment]
It matches the patterns of others components in Elements and allows for better public APIs for some of these chart types (as some options only apply to certain chart types).

Consistency is going to be key for Elements.

**Comment by ebidel** [comment]
I think for this component though you'd have a lot of duplication. You could create  a base element to do most of the business logic, but it wouldn't be very useful by itself (as opposed to an element like google-apis). Plus, it's nice to just change a `type` property and get a new type of chart.

**Comment by krainboltgreene** [comment]
Yes, sure you'd some duplication (I mean that happens a lot already: `<paper-header-panel>` `<paper-scroll-header-panel>` `<paper-dropdown-menu>` `<paper-menu>` `<gold-phone-input>` `<gold-email-input>` `<gold-zip-input input>`)

**Comment by krainboltgreene** [comment]
Also, re: base object, there's a few of those already.

**Comment by wesalvaro** [comment]
I think that certainly google-chart could be a behavior, but I think overall, the current setup is consistent with an input element with a type attribute.
