### ISSUE TITLE
iron-ajax dependency is restricting to version 1.0.0

### ISSUE THREAD

**Issue by deedubbu** [GoogleWebComponents/google-chart#59]
The dependency for iron-ajax in bower.json is configured as `PolymerElements/iron-ajax#1.0.0`. This is forcing bower to use version 1.0.0 and prevents updating to new bug fix versions of iron-ajax. If this was not intentional, would like to see this updated to `PolymerElements/iron-ajax#^1.0.0`.

**Comment by jakemac53** [comment]
I am running into this as well....

**Comment by ebidel** [comment]
Fixed in https://github.com/GoogleWebComponents/google-chart/releases/tag/1.0.3
