### ISSUE TITLE
New select listener added everytime chart is updated

### ISSUE THREAD

**Issue by stmudie** [GoogleWebComponents/google-chart#60]
Every time a chart is updated `google.visualization.events.addListener` is called to add a `google-chart-select` event. This means if the chart is updated several times multiple events are fired for a single selection on the chart.

**Comment by summers173** [comment]
@stmudie is right, I was about add the same observation, there is an issue in here

**Comment by wesalvaro** [comment]
I don't see how this is an issue given that the addListener is gated by the check for the chartObject being null. A new chartObject is created and the listener is attached. The only way for this to be an issue is if the previous, "discarded" chart is still drawn and fires off select events.

The code was recently restructured to more clearly show this behavior and I am not currently able to reproduce this issue.
