### ISSUE TITLE
Re-render chart after type change

### ISSUE THREAD

**Issue by TimWillis** [GoogleWebComponents/google-chart#66]
I would like to be able to have the chart re-rendered when I do a binding to the chart's type

```
<google-chart class="pie" type='{{get_chart_name(count_l1.selected_tab)}}''>
                                        </google-chart>
```
currently this does nothing.

Thanks

**Comment by TimWillis** [comment]
I had a code block above that didn't show up. Anyway, I figured it out, my binding variable was initially undefined when the cart was drawn. Once the var was undefined the element ignored the updated values I put in the var like 'pie',  and would not re-render. I'm leaving this open because it is still sort of a bug as I believe it should have rendered once I changed the binding var from undefined to 'pie'. Feel free to close if this is by design.

**Comment by ebidel** [comment]
On the [demo page](https://elements.polymer-project.org/elements/google-chart?view=demo:demo/index.html), if I change `type="pie"` -> `type="bar"` on the piechart demo, it renders correctly as a bar graph. 

If you provide an undefined chart type, than https://github.com/GoogleWebComponents/google-chart/blob/master/google-chart.html#L254 will fail and not setup your chart. I think this is WAI.
