### ISSUE TITLE
Microsoft Edge / IE10: SCRIPT5007: Object expected osd.js (15,199)

### ISSUE THREAD

**Issue by Aydie** [GoogleWebComponents/google-chart#67]
http://www.wotzilla.com/?playerName=aydie&clanName=&from=2015-10-01&until=2015-10-16

Click on 
Player -> Activity chart
or
Player -> WN8 chart

Those charts work fine in Firefox or Chrome, in Internet explorer / Edge it shows the console error
SCRIPT5007: Object expected osd.js (15,199)
and the charts are messed up.

Any ideas?

**Comment by wesalvaro** [comment]
I believe this issue is related to the referenced issue and cannot be fixed at this layer.
