### ISSUE TITLE
Trouble selecting an item

### ISSUE THREAD

**Issue by enriquecs** [GoogleWebComponents/google-chart#68]
Hello,

I'm trying to add data to an array when I select an item in the graph but when I select one, deselected, and go back to select, the number of elements in the array increases exponentially over 2. I noticed that the graph is not repainted again , so there is no possibility of overlap.

Do you know that can happen?

Here is the code i'm using:

if(this.selection.length != 0){
        var arr = this.rows;
        var sel = this.selection[0].row
        this.param = arr[sel][0]
        var term1 = {};
        term1[this.field] = this.param;
        this.push('filters', { term: term1})
 } 
 if (this._chartObject && this.setSelection) { (breakpoint debugging)
        this._chartObject.setSelection(this.selection);
  }

(this.field property is an auxiliary property that I'm using, and this.filters an auxiliary array)

> this.filters (first selection)
<- [Object]
> this.filters (second selection)
<- [Object, Object]
> this.filters (third selection)
<- [Object, Object, Object, Object, Object, Object, Object, Object]

I took these data into the marked breakpoint and repeated as many times as the array data.

**Comment by enriquecs** [comment]
Anyone has idea about my problem? it is strange, but collapses the web. 

Thanks in advance.

**Comment by ebidel** [comment]
Please post a jsbin that repos the issue. You can use https://polygit.org/ for the imports.

**Comment by enriquecs** [comment]
Ok, actually I've just seen it was my fault, sorry for posting a failed error.
