### ISSUE TITLE
imageUri as property

### ISSUE THREAD

**Issue by zoechi** [GoogleWebComponents/google-chart#71]
I think `getImageUri()` should be provided as property `imageUri` so it can be bound to.

**Comment by ebidel** [comment]
Feel free to PR

**Comment by zoechi** [comment]
Sorry, I'm not used to work with JS, I'm a Dart developer.
I guess this addition wouldn't be too hard by itself, but when I think about testing, ... I'm just not used to JS tool-chain.

**Comment by wesalvaro** [comment]
I don't think this should be a standard property as it takes time to compute the imageUri and I don't think it is useful to many people. Perhaps adding an attribute to enable the updating of such a property?

**Comment by wesalvaro** [comment]
I've created a PR to support this #87.

I measured the time taken for the charts in the demo page and all were very low (<10ms).

However, the charts on the demo page are small. Perhaps with larger charts, the time needed will be much greater... If someone wants to clone and try it out, please do. I don't plan to pursue it as I don't think it is particularly useful given the easy work-around.

**Comment by wesalvaro** [comment]
I'm going to close this since we couldn't get it working ideally.
It's possible to create the image as a computed value on `chart.drawn` as of #127 
Without any other ideas, I think that's a good compromise.
