### ISSUE TITLE
Not working with Polymer 1.2.2

### ISSUE THREAD

**Issue by undermensch** [GoogleWebComponents/google-chart#73]
Chart worked fine until Polymer updated to 1.2.2. Reverting to Polymer 1.2.1, chart again works.

**Comment by ebidel** [comment]
Can you be more specific, also include code snippets? What features are you using?

**Comment by ebidel** [comment]
1.2.2 Just came out so this is a little worrying that something is broken over there.

**Comment by ebidel** [comment]
I just ran the demo page with 1.2.2, and things seem to work. There's an error in the console, but that appears with 1.2.1 as well.

**Comment by undermensch** [comment]
If I place the chart component in a custom component, It will work in Polymer 1.2.1, but not in 1.2.2. In _createDataTable, this.rows is an empty array in 1.2.2, but not in 1.2.1. If I do not place the chart within a custom component, then it works in 1.2.2.
[sample.txt](https://github.com/GoogleWebComponents/google-chart/files/34324/sample.txt)

![chart test](https://cloud.githubusercontent.com/assets/2065843/11156604/dd785c08-8a1a-11e5-84b5-bbb3f4b0ee21.png)

**Comment by jongeho1** [comment]
@ebidel @undermensch - i see no charts rendering when using json inside of single quotes. @ebidel see the `the-el` element template in this issue: https://github.com/GoogleWebComponents/google-chart/issues/72

If I put the json in a property, then it seems to work fine which is probably more common for dynamic data.

Thanks!
@jongeho1

**Comment by jongeho1** [comment]
I think this our scapegoat:

![screen shot 2015-11-13 at 8 55 52 pm](https://cloud.githubusercontent.com/assets/251154/11161381/019b8122-8a49-11e5-860c-fc49ebc79fd8.png)

See - https://github.com/Polymer/polymer/commit/a2c51bf11ed650085adde2be835838dfeab83c28

**Comment by ebidel** [comment]
Didn't match before :) Can you report that to https://github.com/Polymer/polymer/issues/2734?

**Comment by jongeho1** [comment]
@ebidel thank you! :fire: :fire_engine:

**Comment by kevinpschaaf** [comment]
After doing some forensics here, the fact that the repro above worked in `v1.2.0`-`v1.2.1` was an unintended consequence of unrelated changes.  If you test on the release prior to `v1.2.0` (`v1.1.5), it again fails to deserialize the nested JSON array literal.

There has been a longstanding issue https://github.com/Polymer/polymer/issues/1734 regarding Polymer's inability to disambiguate nested JSON array literals from one-way bindings.  The introduction of compound bindings in `v1.2.0` resulted in _some_ (but not all) nested JSON array literals from failing the binding test and thus being deserialized as expected.  However, as a result of https://github.com/Polymer/polymer/pull/2705 (which aimed to make the binding parsing more correct), we again fail to exclude nested JSON arrays.

As such, this isn't a pure regression and the longstanding issue remains.  For the short term, the solution is to avoid JSON literals that overlap with binding syntax (e.g. `[[...]]`) until #2705 is resolved; there are several ways, such as by introducing spaces between the `[`'s of nested arrays or initializing data via properties.

**Comment by wesalvaro** [comment]
The work around using `[ [...] ]` should be used.
