### ISSUE TITLE
discrepancy between shadow and shady dom default + option controlled styling for type "table"

### ISSUE THREAD

**Issue by jongeho1** [GoogleWebComponents/google-chart#74]
Hi there,

I was investigating the possibility of using native shadow dom on some browsers for apps and noticed a discrepancy in style in the "table" type between shadow and shady dom. This impacts things like the ability to freeze columns, hover over background, alternating row styles and default styling.

https://gist.github.com/anonymous/5c99df756ee2f4ec318e

You may comment out line 5 to see the difference.

Let me know if you need any additional info!

Thanks

@jongeho1

**Comment by wesalvaro** [comment]
[A more brief jsbin](https://jsbin.com/xurohojare/edit?output) that demonstrates this behavior.

**Comment by wesalvaro** [comment]
I think this is an issue with Table [google-visualization](https://github.com/google/google-visualization-issues/issues) and cannot be addressed at this layer.

**Comment by wesalvaro** [comment]
This looks like the same issue brought up here: https://github.com/GoogleWebComponents/google-chart/issues/26#issuecomment-69314220 in #26 by @sgomes. There is a PR over there that we can work with.
