### ISSUE TITLE
Charts are not getting drawed at first load

### ISSUE THREAD

**Issue by samcarecho** [GoogleWebComponents/google-chart#76]
Polymer: 1.2.3
google-charts: 1.0.4
polymer-starter-kit: 1.2.0

Let's assume the following code as an example:
```html
<google-chart
    type='column'
    options='{"title": "Responsive chart", "vAxis": {"minValue" : 0, "maxValue": 10}}' 
    cols='[{"label": "Data", "type": "string"},{"label": "Value", "type": "number"}]'
    rows='[["Col1", 5.0],["Col2", 5.0],["Col3", 5.0]]'>
</google-chart>
```

When the page renders on Chrome, the rows attribute is missing and the chart does not render at the first load of the page.
```html
<google-chart 
    type="column" 
    options="{&quot;title&quot;: &quot;Responsive chart&quot;, &quot;vAxis&quot;: {&quot;minValue&quot; : 0, &quot;maxValue&quot;: 10}}" 
    cols="[{&quot;label&quot;: &quot;Data&quot;, &quot;type&quot;: &quot;string&quot;},{&quot;label&quot;: &quot;Value&quot;, &quot;type&quot;: &quot;number&quot;}]">
    <iron-ajax id="ajax" handle-as="json" class="style-scope google-chart" hidden=""></iron-ajax>
    <div id="chartdiv" class="style-scope google-chart"></div>
    <google-legacy-loader class="style-scope google-chart"></google-legacy-loader>
</google-chart>
```

If I inject the rows using the console, as following:
```javascript
$0.rows = [["Col1", 5.0],["Col2", 5.0],["Col3", 5.0]];
```

The chart is drawn.

Is this a bug?

**Comment by ebidel** [comment]
http://jsbin.com/cefemeqoxu/edit?html,output is working for me. What is different about your setup?

**Comment by samcarecho** [comment]
@ebidel it also works for me. 
For instance, when I run the google-chart demo, it works just fine and all the demo charts are displayed.

The problem happens when I run it inside the Starter Kit.
Something is causing the "rows" attribute to be removed from the "google-charts" tag.

I've added the following elements to the project:
```javascript
<link rel="import" href="../bower_components/google-chart/google-chart.html">
<link rel="import" href="../bower_components/google-youtube/google-youtube.html">
<link rel="import" href="../bower_components/google-youtube-upload/google-youtube-upload.html">
<link rel="import" href="../bower_components/parallax-element/parallax-element.html">
<link rel="import" href="../bower_components/google-signin/google-signin.html">
```

I've pushed the entire demo code that I'm working on to:
https://github.com/samcarecho/jourplat.git (branch "demo01")

Thanks for your time and effort. :)

**Comment by ebidel** [comment]
Ok, please report over there. I'm going to close this since the demos and code snippet your shared are working. It could be any number of things, including, build process stripping things out, vulcanization issues, etc.
