### ISSUE TITLE
Reentrancy issues with drawChart method

### ISSUE THREAD

**Issue by maria-le** [GoogleWebComponents/google-chart#81]
[This SO answer uncovers issues with the `drawChart` method](http://stackoverflow.com/a/35365321/1640892).

The author writes:

> `google-chart` itself appears to be buggy. In particular, it's own `drawChart` is not set up to be properly re-entrant. The most obvious problem is that every time the chart draws, it adds an additional selection listener (which causes multiplying `chart-select` events to fire on your application).

    // monkey-patching google-chart
    var gcp = Object.getPrototypeOf(document.createElement('google-chart'));
    gcp.drawChart = function() {
      if (this._canDraw) {
        if (!this.options) {
          this.options = {};
        }
        if (!this._chartObject) {
          var chartClass = this._chartTypes[this.type];
          if (chartClass) {
            this._chartObject = new chartClass(this.$.chartdiv);
            google.visualization.events.addOneTimeListener(this._chartObject, 'ready', function() {
              this.fire('google-chart-render');
            }.bind(this));
            google.visualization.events.addListener(this._chartObject, 'select', function() {
              this.selection = this._chartObject.getSelection();
              this.fire('google-chart-select', {
                selection: this.selection
              });
            }.bind(this));
            if (this._chartObject.setSelection) {
              this._chartObject.setSelection(this.selection);
            }
          }
        }
        if (this._chartObject) {
          this._chartObject.draw(this._dataTable, this.options);
        } else {
          this.$.chartdiv.innerHTML = 'Undefined chart type';
        }
      }
    };

**Comment by ebidel** [comment]
Care to submit a pr?

**Comment by stmudie** [comment]
This is the same as issue #60.

**Comment by wesalvaro** [comment]
I don't think this is true as the selection listener is only attached if the chartObject is newly created.
