### ISSUE TITLE
Enable gantt chart type

### ISSUE THREAD

**Issue by RyanWhite04** [GoogleWebComponents/google-chart#82]
Gantt charts are pretty new on the google charts api, but it would be nice to have support for them in this component.
I'd be happy to add it myself unless someone else is already working on it.

**Comment by wesalvaro** [comment]
Gantt chart package cannot be loaded from `google.visualization`. It requires the use of `google.charts.load` which can only be called once. That means that we must change the way this element works, either by adding an element to specify the needed packages on the page to load or by loading all of the packages.

So, we'll have to hold off on this for now, I think.

**Comment by wesalvaro** [comment]
I'm going to close this issue and wrap it into #30 as the work required is the same to include the new material charts and this chart type as they both load through `google.charts.load`.
