### ISSUE TITLE
Annotation chart not possible to display more than one type of data

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleWebComponents/google-chart#98]
Challenge some of the data has different value ranges like temperature and pressure, today the only option is to put them in the same scale which make the plot unreadable. Several vertical tracks will be preferred option, another option will be to manage several scales on the same track.

**Comment by ebidel** [comment]
Please provide a jsbin that repos the issue.

**Comment by VelizarVESSELINOV** [comment]
Submitted to an unappropriated project
