### ISSUE TITLE
Error when using google-chart-select event with candlestick charts

### ISSUE THREAD

**Issue by emandere** [GoogleWebComponents/google-chart#99]
I am able to load/display a candlestick chart. However I get the following error when I try to listen to the google-chart-select event.

**Error**

type 'EventImpl' is not a subtype of type 'CustomEvent' of 'e'.
#0      ForexMainChart.ready.<anonymous closure> (package:forex/forex_session_main_chart.dart:28:61)
#1      Function._apply (dart:core-patch/function_patch.dart:7)
#2      Function.apply (dart:core-patch/function_patch.dart:28)
#3      _CreateDartFunctionForInteropIgnoreThis.call (dart:js:1453)

**See code below**

class ForexMainChart extends PolymerElement
{
  ForexMainChart.created() : super.created();
  GoogleChart mainChart;
  ready()
  {
    mainChart = $['mainChart'];
    mainChart.type="candlestick";
    mainChart.title="Forex Chart";
    mainChart.cols=[ {"type":"string"},{"type":"number"},{"type":"number"},{"type":"number"},{"type":"number"}];
    mainChart.rows=[["MON", 20, 28, 38, 45]];
    
  **mainChart.on['google-chart-select'].listen((CustomEvent e) {
      window.alert(e.detail['selection'].toString());
    });**
  }

**Comment by wesalvaro** [comment]
This looks like a bug in your code and not specific to Candlestick charts.

    mainChart.on['google-chart-select'].listen((CustomEvent e) {
      window.alert(e.detail['selection'].toString());
    });

I'm not a Dart person, but it looks like the error is because the event fired is not a `CustomEvent`, it's an `EventImpl`. If this is not correct, you will have to talk to the Polymer team as the event type is not specified in this component.
